Improve dl script

diff --git a/dl b/dl
--- a/dl
+++ b/dl
@@ -1,10 +1,32 @@
 #!/bin/sh
 
+set -e
+
 url="$1"
 filename="${url##*/}"
 
-if command -v bar > /dev/null 2>&1; then
-    hget "$url" 2>&1 > "$filename" | bar
-else
-    hget "$url" > "$filename"
+if [ ! "$filename" ]; then
+    echo "usage: ${0##*/} <url>"
+    exit 1
 fi
+
+if [ -e "$filename" ]; then
+    echo "Error: file already exists at destination" >&2
+    exit 1
+fi
+
+temp="/tmp/$filename.dl"
+
+cleanup() {
+    rm -f "$temp"
+}
+
+trap cleanup EXIT
+
+if command -v bar > /dev/null 2>&1; then
+    hget "$url" 2>&1 > "$temp" | bar "$filename"
+else
+    hget "$url" > "$temp"
+fi
+
+mv "$temp" "$filename"
